#!/usr/bin/env bash
# Runs the CABT adapter verification suite: Java prompt/audit/exporter tests,
# then the Python package tests against fixtures regenerated by the Java run.
#
# Layers and gaps are documented in
# Mage.Server.Plugins/Mage.Player.AI/docs/cabt-verification.md.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODULE="Mage.Server.Plugins/Mage.Player.AI"
MODULE_DIR="$ROOT/$MODULE"
PYTHON_DIR="$ROOT/python"

step() {
    printf '\n=== %s ===\n' "$1"
}

step "Java: mage.player.cabt unit, callback-boundary and full-engine smoke tests"
# the module's test tree contains only the CABT adapter tests: the
# CabtBridgePlayer*Test classes are the callback-boundary integration layer,
# and CabtRealGameSmokeTest runs real GameImpl games through the bridge
mvn -q -pl "$MODULE" test -f "$ROOT/pom.xml"
echo "Java tests passed."

step "Python: refresh cross-language fixtures from the Java test output"
FIXTURES_SRC="$MODULE_DIR/target/cabt-fixtures"
FIXTURES_DST="$PYTHON_DIR/tests/fixtures"
if [ -f "$FIXTURES_SRC/card_data_response.json" ] && [ -f "$FIXTURES_SRC/dataset_sample.jsonl" ]; then
    cp "$FIXTURES_SRC/card_data_response.json" "$FIXTURES_SRC/dataset_sample.jsonl" "$FIXTURES_DST/"
    # card-identity fixtures only exist when the DB-backed test ran (i.e. the
    # card database was scannable); refresh them when present.
    for identity_fixture in validate_deck_response.json global_card_data_response.json; do
        if [ -f "$FIXTURES_SRC/$identity_fixture" ]; then
            cp "$FIXTURES_SRC/$identity_fixture" "$FIXTURES_DST/"
        fi
    done
    echo "Fixtures refreshed from $FIXTURES_SRC."
else
    echo "WARNING: Java-generated fixtures not found under $FIXTURES_SRC;"
    echo "         Python tests will run against the checked-in fixture copies."
fi

step "Python: magic_cabt unit tests"
if command -v python3 >/dev/null 2>&1; then
    (cd "$PYTHON_DIR" && python3 -m unittest discover -s tests)
else
    echo "ERROR: python3 not found; cannot run the Python layer." >&2
    exit 1
fi

step "Python: protocol smoke tests"
PROTOCOL_CLASS="$MODULE_DIR/target/classes/mage/player/cabt/CabtProtocolServer.class"
if [ -f "$PROTOCOL_CLASS" ]; then
    # build the launch classpath for the CabtProtocolServer subprocess:
    # the module's classes plus its full dependency set
    DEPS_FILE="$MODULE_DIR/target/cabt-classpath.txt"
    FULL_CP_FILE="$MODULE_DIR/target/cabt-classpath.full.txt"
    if [ ! -f "$DEPS_FILE" ] || [ "$MODULE_DIR/pom.xml" -nt "$DEPS_FILE" ]; then
        mvn -q -pl "$MODULE" -f "$ROOT/pom.xml" dependency:build-classpath \
            -Dmdep.outputFile="$DEPS_FILE"
    fi
    MAGIC_CABT_CLASSPATH="$MODULE_DIR/target/classes:$(cat "$DEPS_FILE")"
    printf '%s' "$MAGIC_CABT_CLASSPATH" > "$FULL_CP_FILE"
    export MAGIC_CABT_CLASSPATH
    echo "MAGIC_CABT_CLASSPATH written to $FULL_CP_FILE"
    (cd "$PYTHON_DIR" && python3 -m unittest discover -s tests -p "test_protocol*.py")
else
    echo "SKIPPED: no protocol entry point at $PROTOCOL_CLASS"
    echo "         (build the Java module first: mvn -pl $MODULE compile)."
fi

step "CABT adapter verification suite passed"
