#!/usr/bin/env bash
# Runs the CABT adapter verification suite: Java prompt/audit/exporter tests,
# then the Python package tests against fixtures regenerated by the Java run.
#
# Layers and gaps are documented in
# Mage.Server.Plugins/Mage.Player.AI/docs/cabt-verification.md.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODULE="Mage.Server.Plugins/Mage.Player.AI"
MODULE_DIR="$ROOT/$MODULE"
PYTHON_DIR="$ROOT/python"

step() {
    printf '\n=== %s ===\n' "$1"
}

step "Java: mage.player.cabt unit, callback-boundary and full-engine smoke tests"
# the module's test tree contains only the CABT adapter tests: the
# CabtBridgePlayer*Test classes are the callback-boundary integration layer,
# and CabtRealGameSmokeTest runs real GameImpl games through the bridge
mvn -q -pl "$MODULE" test -f "$ROOT/pom.xml"
echo "Java tests passed."

step "Python: refresh cross-language fixtures from the Java test output"
FIXTURES_SRC="$MODULE_DIR/target/cabt-fixtures"
FIXTURES_DST="$PYTHON_DIR/tests/fixtures"
if [ -f "$FIXTURES_SRC/card_data_response.json" ] && [ -f "$FIXTURES_SRC/dataset_sample.jsonl" ]; then
    cp "$FIXTURES_SRC/card_data_response.json" "$FIXTURES_SRC/dataset_sample.jsonl" "$FIXTURES_DST/"
    echo "Fixtures refreshed from $FIXTURES_SRC."
else
    echo "WARNING: Java-generated fixtures not found under $FIXTURES_SRC;"
    echo "         Python tests will run against the checked-in fixture copies."
fi

step "Python: magic_cabt unit tests"
if command -v python3 >/dev/null 2>&1; then
    (cd "$PYTHON_DIR" && python3 -m unittest discover -s tests)
else
    echo "ERROR: python3 not found; cannot run the Python layer." >&2
    exit 1
fi

step "Python: protocol smoke tests"
# the subprocess protocol server is Task 18, which has not been delivered
# yet; this stanza enables itself once the protocol entry point is built
PROTOCOL_CLASS="$MODULE_DIR/target/classes/mage/player/cabt/CabtProtocolServer.class"
if [ -f "$PROTOCOL_CLASS" ]; then
    (cd "$PYTHON_DIR" && python3 -m unittest discover -s tests -p "test_protocol*.py")
else
    echo "SKIPPED: no protocol entry point at $PROTOCOL_CLASS"
    echo "         (subprocess protocol is Task 18; not delivered yet)."
fi

step "CABT adapter verification suite passed"
