import { useCallback,useEffect,useRef,useState } from 'react';
import { api } from './api';
import { example } from './example';
import { parseFile } from './importer';
import { humanPhase,nextPosition,safeView,type Replay,type ReplayRow,type Card,type View } from './domain';
import { useAnalysis } from './useAnalysis';
import { Modal } from './Modal';

const message=(e:unknown)=>e instanceof Error?e.message:'Something went wrong.';
type OpenReplay={id:string|null;replay:Replay};
type Dialog='import'|'settings'|null;
function CardTile({card,art,onInspect}:{card:Card;art:Record<string,string>;onInspect:(c:Card)=>void}){
  const image=art[card.name];
  return <button className={'game-card '+(card.tapped?'tapped ':'')+(card.faceDown?'hidden-card':'')} onClick={()=>onInspect(card)} aria-label={card.name+(card.tapped?', tapped':'')} title={card.name}>
    <span className="card-art" style={image&&!card.faceDown?{backgroundImage:`url(/example-art/${image}.jpg)`}:undefined}><span className="card-mana">{card.mana.replace(/[{}]/g,'')}</span></span>
    <span className="card-name">{card.name}</span><span className="card-type">{card.type.replace('CardType_','')}</span>
    <span className="card-bottom"><span>{card.tapped?'TAPPED':card.attacking?'ATTACKING':''}</span>{card.power!==null&&card.toughness!==null&&<b>{card.power}/{card.toughness}</b>}</span>
  </button>;
}
function PlayerBar({view,seat}:{view:View;seat:string}){const p=view.players.find(p=>p.id===seat);return <div className="player-bar"><span className={'avatar '+(seat===view.viewer?'hero-avatar':'')}>{seat===view.viewer?'Y':'O'}</span><strong>{seat===view.viewer?'You':seat==='public'?'Public view':'Opponent'}</strong><span className="muted">{p?.handCount??'—'} in hand · {p?.libraryCount??'—'} in library</span><span className="priority-chip">{view.priority===seat?'Priority':view.active===seat?'Active turn':''}</span><b className="life">{p?.life??'—'}<small>life</small></b></div>}
function Settings({hasKey,onSaved,onClose}:{hasKey:boolean;onSaved:(v:boolean)=>void;onClose:()=>void}){
 const [key,setKey]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(remove=false){setBusy(true);setError('');try{await api('/key',remove?'DELETE':'PUT',remove?{}:{key:key.trim()});setKey('');onSaved(!remove);onClose()}catch(e){setError(message(e))}finally{setBusy(false)}}
 return <Modal title="Analysis settings" onClose={onClose}><p>Your OpenRouter key is encrypted on the server. It stays saved between visits.</p><form onSubmit={e=>{e.preventDefault();void save()}}><label htmlFor="key">{hasKey?'Replace saved key':'OpenRouter key'}</label><input id="key" type="password" autoComplete="off" placeholder={hasKey?'A key is already saved':'sk-or-…'} value={key} onChange={e=>setKey(e.target.value)}/><p className="hint">Only replay positions you choose to analyze are sent to OpenRouter / TypeSafe. Jev’s scores are not verified win rates.</p><div role="alert" className="form-error">{error}</div><footer className="dialog-actions">{hasKey&&<button type="button" className="quiet" disabled={busy} onClick={()=>void save(true)}>Remove key</button>}<button className="primary stable-button" disabled={busy||!key.trim()}>{busy?'Saving…':'Save key'}</button></footer></form></Modal>
}
function ImportDialog({onClose,onImported}:{onClose:()=>void;onImported:(items:Replay[])=>void}){
 const [kind,setKind]=useState<'arena'|'mtgo'|'json'>('arena'),[busy,setBusy]=useState(false),[error,setError]=useState('');const abort=useRef(new AbortController());
 useEffect(()=>()=>abort.current.abort(),[]);
 async function choose(file?:File){if(!file)return;setBusy(true);setError('');try{const replays=await parseFile(file,kind,abort.current.signal);if(!abort.current.signal.aborted)onImported(replays)}catch(e){if(!abort.current.signal.aborted)setError(message(e))}finally{if(!abort.current.signal.aborted)setBusy(false)}}
 return <Modal title="Import a replay" onClose={onClose}><label htmlFor="format">Source</label><select id="format" value={kind} onChange={e=>setKind(e.target.value as typeof kind)} disabled={busy}><option value="arena">MTG Arena</option><option value="mtgo">MTGO text game log</option><option value="json">Priority replay JSON</option></select>
 {kind==='arena'?<><p>In Arena: <strong>Settings → View Account → Detailed Logs (Plugin Support)</strong>. Restart Arena, then play a game.</p><details><summary>Where is Player.log?</summary><p>Windows</p><code>%USERPROFILE%\AppData\LocalLow\Wizards Of The Coast\MTGA\Player.log</code><p>macOS</p><code>~/Library/Logs/Wizards Of The Coast/MTGA/Player.log</code><p>Logs can be replaced when Arena restarts. Import them before starting another session.</p></details></>:kind==='mtgo'?<p>Choose a copied or exported <strong>text game log</strong>. Native binary .dat files are not supported. Public logs do not contain complete hands or priority choices.</p>:<p>Choose an exported Priority replay. Only perspectives present in the recording will be available.</p>}
 <p className="hint">Your browser cannot search your computer. You choose the file. Parsing stays on this device; nothing uploads until you select Save.</p><div role="alert" className="form-error">{error}</div><label className={'file-button primary '+(busy?'disabled':'')}>{busy?'Reading log…':'Choose file'}<input type="file" accept={kind==='json'?'.json':'.log,.txt'} disabled={busy} onChange={e=>void choose(e.target.files?.[0])}/></label></Modal>
}

export function App(){
 const [rows,setRows]=useState<ReplayRow[]>([]),[opened,setOpened]=useState<OpenReplay|null>(null),[position,setPosition]=useState(0),[seat,setSeat]=useState('1');
 const [dialog,setDialog]=useState<Dialog>(null),[inspect,setInspect]=useState<Card|null>(null),[hasKey,setHasKey]=useState(false),[signedIn,setSignedIn]=useState(false),[notice,setNotice]=useState(''),[working,setWorking]=useState(false),[playing,setPlaying]=useState(false),[auto,setAuto]=useState(false),[search,setSearch]=useState('');
 const [art,setArt]=useState<Record<string,string>>({}),[imports,setImports]=useState<Replay[]>([]),[ratings,setRatings]=useState<Record<string,string>>({});
 const {results,request,cancel}=useAnalysis();const loadGeneration=useRef(0),stepTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const historyRef=useRef<HTMLOListElement>(null);
 const refresh=useCallback(async()=>{try{const session=await api<{hasKey:boolean}>('/session');setSignedIn(true);setHasKey(session.hasKey);setRows(await api<ReplayRow[]>('/replays'));setNotice('')}catch{setSignedIn(false);setNotice('Local preview. Hosted storage requires Cloudflare Access.')}},[]);
 useEffect(()=>{void refresh();void fetch('/example-art.json').then(r=>r.ok?r.json():{}).then(setArt).catch(()=>{});return()=>{if(stepTimer.current)clearTimeout(stepTimer.current)}},[refresh]);
 const replay=opened?.replay,frame=replay?.frames[position],available=frame?Object.keys(frame.views):[];
 const actualSeat=available.includes(seat)?seat:available[0];
 const view=frame&&actualSeat?safeView(frame.views[actualSeat]):null,decision=frame&&actualSeat?frame.decisions[actualSeat]:null;
 const key=opened?.id+':'+position+':'+actualSeat,result=results[key],sample=replay?.source==='example';
 const eligible=!!opened?.id&&!sample&&!!view&&view.priority===actualSeat&&!!decision?.supported&&decision.min===1&&decision.max===1;
 const move=useCallback((target:number,manual=true)=>{if(!opened)return;cancel();if(stepTimer.current)clearTimeout(stepTimer.current);setPosition(target);setPlaying(false);if(manual&&auto&&hasKey&&opened.id&&opened.replay.source!=='example'){const f=opened.replay.frames[target],p=Object.keys(f.views).includes(seat)?seat:Object.keys(f.views)[0];if(f.decisions[p]?.supported&&f.views[p]?.priority===p)stepTimer.current=setTimeout(()=>request(opened.id!,target,p),100)}},[opened,auto,hasKey,seat,request,cancel]);
 function selectReplay(replay:Replay,id:string|null){cancel();if(stepTimer.current)clearTimeout(stepTimer.current);setOpened({replay,id});setPosition(0);setSeat(Object.keys(replay.frames[0].views)[0]);setPlaying(false);setInspect(null);setNotice('')}
 async function openSaved(id:string){const generation=++loadGeneration.current;setWorking(true);try{const r=await api<Replay>('/replays/'+id);if(generation===loadGeneration.current)selectReplay(r,id)}catch(e){setNotice(message(e))}finally{if(generation===loadGeneration.current)setWorking(false)}}
 function leave(){cancel();if(stepTimer.current)clearTimeout(stepTimer.current);setPlaying(false);setOpened(null);setInspect(null);loadGeneration.current++}
 useEffect(()=>{if(!playing||!replay)return;const timer=setInterval(()=>setPosition(p=>{if(p>=replay.frames.length-1){setPlaying(false);return p}return p+1}),900);return()=>clearInterval(timer)},[playing,replay]);
 useEffect(()=>{function keyboard(e:KeyboardEvent){if(!replay||dialog||inspect||imports.length||e.altKey||e.ctrlKey||e.metaKey||e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement||e.target instanceof HTMLTextAreaElement)return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();move(nextPosition(replay,position,e.key==='ArrowRight'?1:-1,e.shiftKey))}else if(e.key===' '){e.preventDefault();cancel();setPlaying(v=>!v)}else if(e.key==='Home'||e.key==='End'){e.preventDefault();move(e.key==='Home'?0:replay.frames.length-1)}}window.addEventListener('keydown',keyboard);return()=>window.removeEventListener('keydown',keyboard)},[replay,dialog,inspect,imports.length,position,move,cancel]);
 useEffect(()=>{const list=historyRef.current,node=list?.querySelector<HTMLElement>('[aria-current="step"]');if(list&&node){const top=node.offsetTop-list.offsetTop;if(top<list.scrollTop||top+node.offsetHeight>list.scrollTop+list.clientHeight)list.scrollTop=Math.max(0,top-list.clientHeight/2)}},[position]);
 async function saveImports(){setWorking(true);setNotice('');try{let last:{id:string}|undefined;for(const item of imports)last=await api<{id:string}>('/replays','POST',item);const saved=imports[imports.length-1];setImports([]);await refresh();if(last)selectReplay(saved,last.id)}catch(e){setNotice(message(e))}finally{setWorking(false)}}
 async function rate(value:string){if(!opened?.id)return;setWorking(true);try{await api('/replays/'+opened.id+'/rating','PUT',{position,perspective:actualSeat,rating:value});setRatings(r=>({...r,[key]:value}));setNotice('')}catch(e){setNotice(message(e))}finally{setWorking(false)}}
 async function remove(id:string){setWorking(true);try{await api('/replays/'+id,'DELETE',{});setRows(r=>r.filter(x=>x.id!==id));setNotice('')}catch(e){setNotice(message(e))}finally{setWorking(false)}}
 const opponent=view?.players.find(p=>p.id!==view.viewer)?.id;
 return <div className="app-shell"><header className="app-header"><div className="brand"><span className="brand-mark">P</span><span>PRIORITY</span></div>{opened?<><button className="icon back" aria-label="Back to library" onClick={leave}>←</button><div className="heading"><strong>{replay?.title}</strong><span>{sample?'Interface example':replay?.source==='mtgo'?'Public log reconstruction':'Recorded replay'}</span></div></>:<div className="heading"><strong>Your replay library</strong><span>Review the position. Understand the choice.</span></div>}<div className="header-actions"><button onClick={()=>{setPlaying(false);cancel();setDialog('import')}}>Import</button><button className="icon" aria-label="Settings" onClick={()=>{setPlaying(false);cancel();setDialog('settings')}}>⚙</button></div></header>
 <div className="notice" role="status">{notice}</div>
 {!opened?<main className="library"><div className="library-heading"><div><p className="eyebrow">THE REVIEW ROOM</p><h1>A better look at your game.</h1><p className="muted">Your games, their decisions, and what comes next.</p></div><button className="primary" onClick={()=>setDialog('import')}>Import a game <span>↗</span></button></div><div className="library-tools"><h2>Recent replays <span>{rows.length}</span></h2><input type="search" aria-label="Search replays" placeholder="Find a game" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="replay-list">{rows.filter(r=>r.title.toLowerCase().includes(search.toLowerCase())).map(r=><article className="replay-row" key={r.id}><button className="replay-open" disabled={working} onClick={()=>void openSaved(r.id)}><span className="replay-symbol">↻</span><span><strong>{r.title}</strong><small>{r.source.toUpperCase()} · {r.frames} positions</small></span><time>{new Date(r.created_at).toLocaleDateString()}</time><span>→</span></button><button className="icon delete" aria-label={'Delete '+r.title} disabled={working} onClick={()=>{if(confirm('Delete this saved replay?'))void remove(r.id)}}>×</button></article>)}{rows.length===0&&<div className="empty-library"><span className="empty-mark">◫</span><h3>Your next insight starts here.</h3><p>Import a log, or explore the viewer with an example.</p><button onClick={()=>selectReplay(example,null)}>Explore example →</button></div>}</div><p className="library-foot">{signedIn?'Private to your account · Latest 200 replays':'No account needed to preview a local replay.'}</p></main>:frame&&view?<main className="workspace"><section className="board-column" aria-label="Replay board"><div className="board-toolbar"><span className="eyebrow">TURN {frame.turn}</span><strong>{humanPhase(frame.phase)||'Position'}</strong><select aria-label="Perspective" value={actualSeat} onChange={e=>{cancel();setPlaying(false);setSeat(e.target.value);setInspect(null)}}>{available.map(p=><option key={p} value={p}>{p==='public'?'Public view':'Player '+p+' perspective'}</option>)}</select></div>
 <div className="battlefield"><div className="board-half opponent-half">{opponent&&<PlayerBar view={view} seat={opponent}/>}<div className="card-lane">{view.cards.filter(c=>c.zone==='battlefield'&&c.controller!==view.viewer).map(c=><CardTile key={c.ref} card={c} art={art} onInspect={setInspect}/>)}{view.cards.filter(c=>c.zone==='battlefield'&&c.controller!==view.viewer).length===0&&<span className="zone-empty">Opponent battlefield</span>}</div></div><div className="stack-lane"><span>STACK</span>{view.cards.filter(c=>c.zone==='stack').length?view.cards.filter(c=>c.zone==='stack').map(c=><button key={c.ref} onClick={()=>setInspect(c)}>{c.name}</button>):<small>Empty</small>}</div><div className="board-half hero-half"><div className="card-lane">{view.cards.filter(c=>c.zone==='battlefield'&&c.controller===view.viewer).map(c=><CardTile key={c.ref} card={c} art={art} onInspect={setInspect}/>)}{view.cards.filter(c=>c.zone==='battlefield'&&c.controller===view.viewer).length===0&&<span className="zone-empty">Your battlefield</span>}</div><PlayerBar view={view} seat={view.viewer}/></div></div>
 <div className="hand-area"><span className="eyebrow">{view.viewer==='public'?'PUBLIC RECORDING':'YOUR HAND'}</span><div className="hand-lane">{view.players.find(p=>p.id===view.viewer)?.hand.map(c=><CardTile key={c.ref} card={c} art={art} onInspect={setInspect}/>)}{!view.players.find(p=>p.id===view.viewer)?.hand.length&&<span className="zone-empty">No visible hand cards in this position</span>}</div></div>
 <details className="other-zones"><summary>Graveyards, exile & known information <span>{view.cards.filter(c=>!['battlefield','stack'].includes(c.zone)).length} cards</span></summary><div>{view.cards.filter(c=>!['battlefield','stack'].includes(c.zone)).map(c=><button key={c.ref} onClick={()=>setInspect(c)}>{c.name}<small>{c.zone}</small></button>)}{view.known.map((text,i)=><p key={i}>{text}</p>)}</div></details>
 <footer className="transport"><div className="transport-buttons"><button aria-label="First position" disabled={position===0} onClick={()=>move(0)}>⇤</button><button aria-label="Previous position" disabled={position===0} onClick={()=>move(position-1)}>←</button><button className="play" aria-label={playing?'Pause replay':'Play replay'} disabled={position===replay!.frames.length-1&&!playing} onClick={()=>{cancel();setPlaying(p=>!p)}}>{playing?'Ⅱ':'▶'}</button><button aria-label="Next position" disabled={position===replay!.frames.length-1} onClick={()=>move(position+1)}>→</button><button aria-label="Next decision" disabled={position===replay!.frames.length-1} onClick={()=>move(nextPosition(replay!,position,1,true))}>⇥</button></div><input aria-label="Replay position" type="range" min={0} max={replay!.frames.length-1} value={position} onChange={e=>move(Number(e.target.value))}/><span className="position-count">{position+1} / {replay!.frames.length}</span></footer></section>
 <aside className="analysis-column" aria-label="Analysis panel"><section className="analysis-box"><div className="section-title"><h2>Analysis</h2><span className="model-chip">JEV</span></div><div className="analysis-state" role="status">{sample?<><strong>A place to test your instincts.</strong><p>This is an interface example. Import your own game to ask Jev.</p></>:!decision?<><strong>No captured decision</strong><p>Step to a priority point to compare legal choices.</p></>:!decision.supported?<><strong>Not analyzable</strong><p>{decision.reason}</p></>:result?.status==='pending'?<><strong>Analyzing the position…</strong><p>You can keep stepping.</p></>:result?.status==='error'?<><strong>Analysis unavailable</strong><p>{result.error}</p></>:result?.status==='done'?<><strong>{decision.options.find(o=>o.id===result.choice)?.label}</strong><p>{decision.chosen?.includes(result.choice!)?'Matches your recorded choice.':'Different from your recorded choice.'}</p></>:<><strong>{decision.options.length} captured choices</strong><p>Choose Analyze to review this position.</p></>}</div><div className="analysis-actions">{!hasKey&&eligible?<button className="primary" onClick={()=>setDialog('settings')}>Connect OpenRouter</button>:<button className="primary" disabled={!eligible||!hasKey||result?.status==='pending'||result?.status==='done'} onClick={()=>request(opened.id!,position,actualSeat,result?.status==='error')}>{result?.status==='pending'?'Analyzing…':result?.status==='error'?'Retry analysis':'Analyze'}</button>}<label className="auto-control"><input type="checkbox" checked={auto} disabled={!hasKey} onChange={e=>{cancel();setAuto(e.target.checked)}}/> After stepping</label></div><div className="options-list">{decision?.options.map(o=><div className={'option '+(result?.choice===o.id?'recommended':'')} key={o.id}><div><strong>{o.label}</strong>{decision.chosen?.includes(o.id)&&<span className="played-chip">Played</span>}</div><span>{result?.probabilities?.[o.id]!==undefined?(result.probabilities[o.id]*100).toFixed(1)+'%':'—'}</span></div>)}</div><div className="analysis-metrics"><span>{result?.latency!=null?result.latency+' ms':'Latency —'}</span><span>{result?.cost!=null?'$'+result.cost.toFixed(6):'Cost —'}</span></div><label className="rating">Your review <select aria-label="Rate analysis" disabled={!opened.id||!result||result.status!=='done'||working} value={ratings[key]||'unrated'} onChange={e=>void rate(e.target.value)}><option value="unrated">Not rated</option><option value="useful">Useful</option><option value="wrong">Wrong</option><option value="unsure">Unsure</option></select></label><p className="score-note">Choice scores, not win probabilities.</p></section>
 <section className="move-history"><div className="section-title"><h2>Timeline</h2><span>{replay!.frames.length} positions</span></div><ol ref={historyRef}>{replay!.frames.map((f,i)=><li key={i}><button aria-current={i===position?'step':undefined} onClick={()=>move(i)}><span>{i+1}</span><span>{f.label}</span><small>T{f.turn}</small></button></li>)}</ol></section><details className="capture-notes"><summary>Recording details</summary>{replay!.warnings.concat(frame.warnings).map((w,i)=><p key={i}>{w}</p>)}</details></aside></main>:<main className="fatal"><h2>This perspective is unavailable.</h2><button onClick={leave}>Back to library</button></main>}
 {dialog==='settings'&&<Settings hasKey={hasKey} onSaved={setHasKey} onClose={()=>setDialog(null)}/>} {dialog==='import'&&<ImportDialog onClose={()=>setDialog(null)} onImported={r=>{setDialog(null);setImports(r)}}/>}
 {imports.length>0&&<Modal title="Ready to review" onClose={()=>setImports([])}><p>{imports.length} game{imports.length===1?'':'s'} parsed on your device.</p><div className="import-summary">{imports.map((r,i)=><div key={i}><strong>{r.title}</strong><span>{r.frames.length} positions</span>{r.warnings.map((w,j)=><p key={j}>{w}</p>)}</div>)}</div><p className="hint">Save uploads only the parsed replay to your private library. The original log stays on your device.</p><p role="alert">{notice}</p><footer className="dialog-actions"><button onClick={()=>{selectReplay(imports[0],null);setImports([])}}>Preview locally</button><button className="primary" disabled={!signedIn||working} onClick={()=>void saveImports()}>{working?'Saving…':'Save to library'}</button></footer></Modal>}
 {inspect&&<Modal title={inspect.name} onClose={()=>setInspect(null)}><p className="card-inspect-type">{inspect.type} <span>{inspect.mana}</span></p><p className="rules-text">{inspect.rules||'Rules text is not available in this recording.'}</p><p className="hint">{inspect.zone} · {inspect.tapped?'Tapped':'Untapped'}{inspect.damage?' · '+inspect.damage+' damage':''}{inspect.attachedTo?' · Attached to '+inspect.attachedTo:''}</p>{Object.entries(inspect.counters).map(([k,v])=><p key={k}>{k}: {v}</p>)}</Modal>}
 </div>
}
