import { ReplaySchema, CardSchema, type Card, type View } from './domain';
const card=(name:string,ref:string,owner:string,zone:Card['zone'],extra:Partial<Card>={})=>CardSchema.parse({name,ref,owner,controller:owner,zone,...extra});
const mountain=card('Mountain','mountain-1','1','battlefield',{type:'Basic Land — Mountain',rules:'{T}: Add {R}.'});
const island=card('Island','island-1','2','battlefield',{type:'Basic Land — Island',rules:'{T}: Add {U}.'});
const bolt=card('Lightning Bolt','bolt-1','1','hand',{type:'Instant',mana:'{R}',rules:'Lightning Bolt deals 3 damage to any target.'});
const swiftspear=card('Monastery Swiftspear','swiftspear-1','1','battlefield',{type:'Creature — Human Monk',power:1,toughness:2,rules:'Haste\nProwess'});
const delver=card('Delver of Secrets','delver-1','2','battlefield',{type:'Creature — Human Wizard',power:1,toughness:1,rules:'At the beginning of your upkeep, look at the top card of your library. You may reveal that card. If an instant or sorcery card is revealed this way, transform Delver of Secrets.'});
const base:View={viewer:'1',active:'1',priority:'1',players:[{id:'1',life:16,handCount:3,libraryCount:49,hand:[bolt,card('Mountain','mountain-2','1','hand',{type:'Basic Land — Mountain'}),card('Lava Spike','lava-1','1','hand',{mana:'{R}',type:'Sorcery',rules:'Lava Spike deals 3 damage to target player or planeswalker.'})],revealedHand:[]},{id:'2',life:12,handCount:4,libraryCount:50,hand:[],revealedHand:[]}],cards:[mountain,island,swiftspear,delver],known:[]};
export const example=ReplaySchema.parse({version:1,title:'Burn vs Delver',source:'example',warnings:['Interface example — not recorded gameplay or a Jev result.'],frames:Array.from({length:12},(_,i)=>({turn:Math.floor(i/3)+1,phase:['Main 1','Declare attackers','End step'][i%3],label:['Play Mountain','Cast Monastery Swiftspear','Pass priority','Play Island','Cast Delver of Secrets','Pass priority','Play Mountain','Cast Lightning Bolt','Pass priority','Declare attackers','Pass priority','End turn'][i],views:{'1':{...base,cards:base.cards.map(c=>({...c,tapped:c.ref==='swiftspear-1'&&i>8})),active:i%6<3?'1':'2',priority:'1'}},decisions:{'1':{kind:'PRIORITY',min:1,max:1,source:'arena-captured',supported:true,options:[{id:'pass',label:'Pass priority',detail:''},{id:'bolt',label:'Cast Lightning Bolt',detail:'Targets are selected in a later prompt.'},{id:'land',label:'Play Mountain',detail:''}],chosen:[i%2?'pass':'bolt']}},warnings:[]}))});
